name: AngelBlock
version: 1.2
main: top.mistmc.angelblock.Angelblock
api-version: 1.21
description: 天使方块插件，允许在空中放置特殊方块
author: mc506lw
folia-supported: true
softdepend:
  - HuskClaims
  - Dominion

commands:
  angelblock:
    description: 获取或管理天使方块
    usage: |
      /angelblock - 给自己天使方块
      /angelblock <玩家> - 给指定玩家天使方块
      /angelblock reload - 重载配置文件
      /angelblock removeall - 移除自己的天使方块
      /angelblock removeall <玩家> - 移除指定玩家的天使方块（需要权限）
      /angelblock removeall @a - 移除所有玩家的天使方块（需要权限）
      /angelblock removeall @r - 移除随机玩家的天使方块（需要权限）
    aliases: [ab]
    permission: angelblock.use
    permission-message: "&c你没有权限使用此命令！"

permissions:
  angelblock.give:
    description: 允许给自己或他人天使方块
    default: op
  angelblock.use:
    description: 允许使用天使方块
    default: true
  angelblock.reload:
    description: 允许重载插件配置
    default: op
  angelblock.admin:
    description: 所有插件管理权限
    default: op
  angelblock.removeall:
    description: 允许移除所有天使方块
    default: true
  angelblock.removeall.others:
    description: 允许移除其他玩家的天使方块
    default: op
  angelblock.max.*:
    description: 允许无限放置天使方块
    default: op
  angelblock.max.unlimited:
    description: 允许无限放置天使方块
    default: op